/* Generated by www.jsonschema2pojo.org with example requests sent to the github API v3. */
package de.lmu.ifi.bio.watchdog.validator.github.autogen.commit;


public class Tree {

    private String sha;
    private String url;

    public String getSha() {
        return sha;
    }

    public void setSha(String sha) {
        this.sha = sha;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

}
