/* Generated by www.jsonschema2pojo.org with example requests sent to the github API v3. */
package de.lmu.ifi.bio.watchdog.validator.github.autogen.compare;


public class Commit___ {

    private Author____ author;
    private Committer____ committer;
    private String message;
    private Tree__ tree;
    private String url;
    private Integer commentCount;
    private Verification__ verification;

    public Author____ getAuthor() {
        return author;
    }

    public void setAuthor(Author____ author) {
        this.author = author;
    }

    public Committer____ getCommitter() {
        return committer;
    }

    public void setCommitter(Committer____ committer) {
        this.committer = committer;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public Tree__ getTree() {
        return tree;
    }

    public void setTree(Tree__ tree) {
        this.tree = tree;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public Integer getCommentCount() {
        return commentCount;
    }

    public void setCommentCount(Integer commentCount) {
        this.commentCount = commentCount;
    }

    public Verification__ getVerification() {
        return verification;
    }

    public void setVerification(Verification__ verification) {
        this.verification = verification;
    }

}
