/* Generated by www.jsonschema2pojo.org with example requests sent to the github API v3. */
package de.lmu.ifi.bio.watchdog.validator.github.autogen.compare;

import java.util.List;

public class Commit__ {

    private String sha;
    private String nodeId;
    private Commit___ commit;
    private String url;
    private String htmlUrl;
    private String commentsUrl;
    private Author_____ author;
    private Committer_____ committer;
    private List<Parent__> parents = null;

    public String getSha() {
        return sha;
    }

    public void setSha(String sha) {
        this.sha = sha;
    }

    public String getNodeId() {
        return nodeId;
    }

    public void setNodeId(String nodeId) {
        this.nodeId = nodeId;
    }

    public Commit___ getCommit() {
        return commit;
    }

    public void setCommit(Commit___ commit) {
        this.commit = commit;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getHtmlUrl() {
        return htmlUrl;
    }

    public void setHtmlUrl(String htmlUrl) {
        this.htmlUrl = htmlUrl;
    }

    public String getCommentsUrl() {
        return commentsUrl;
    }

    public void setCommentsUrl(String commentsUrl) {
        this.commentsUrl = commentsUrl;
    }

    public Author_____ getAuthor() {
        return author;
    }

    public void setAuthor(Author_____ author) {
        this.author = author;
    }

    public Committer_____ getCommitter() {
        return committer;
    }

    public void setCommitter(Committer_____ committer) {
        this.committer = committer;
    }

    public List<Parent__> getParents() {
        return parents;
    }

    public void setParents(List<Parent__> parents) {
        this.parents = parents;
    }

}
