/* Generated by www.jsonschema2pojo.org with example requests sent to the github API v3. */
package de.lmu.ifi.bio.watchdog.validator.github.autogen.compare;

import java.util.List;

public class MergeBaseCommit {

    private String sha;
    private String nodeId;
    private Commit_ commit;
    private String url;
    private String htmlUrl;
    private String commentsUrl;
    private Author___ author;
    private Committer___ committer;
    private List<Parent_> parents = null;

    public String getSha() {
        return sha;
    }

    public void setSha(String sha) {
        this.sha = sha;
    }

    public String getNodeId() {
        return nodeId;
    }

    public void setNodeId(String nodeId) {
        this.nodeId = nodeId;
    }

    public Commit_ getCommit() {
        return commit;
    }

    public void setCommit(Commit_ commit) {
        this.commit = commit;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getHtmlUrl() {
        return htmlUrl;
    }

    public void setHtmlUrl(String htmlUrl) {
        this.htmlUrl = htmlUrl;
    }

    public String getCommentsUrl() {
        return commentsUrl;
    }

    public void setCommentsUrl(String commentsUrl) {
        this.commentsUrl = commentsUrl;
    }

    public Author___ getAuthor() {
        return author;
    }

    public void setAuthor(Author___ author) {
        this.author = author;
    }

    public Committer___ getCommitter() {
        return committer;
    }

    public void setCommitter(Committer___ committer) {
        this.committer = committer;
    }

    public List<Parent_> getParents() {
        return parents;
    }

    public void setParents(List<Parent_> parents) {
        this.parents = parents;
    }

}
