name: update_github_page
'on':
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout master
        uses: klugem/actions_checkout@v2
        with:
          ref: master
          path: master
      - name: checkout gh-pages
        uses: klugem/actions_checkout@v2
        with:
          ref: gh-pages
          path: gh-pages
          token: '${{ secrets.WATCHDOG_WMS_BOT_TOKEN }}'
      - name: create documentation folder
        run: |
          cd "$GITHUB_WORKSPACE"
          rm -rf gh-pages/*
          cp -r master/documentation/* gh-pages/.
          rm -rf gh-pages/module_library_tpl
      - name: commit and push files
        run: |
          cd "$GITHUB_WORKSPACE/gh-pages"
          if [ ! -z "$(git status --porcelain)" ]; then
            curl -H "Authorization: token ${{ secrets.DOWNLOAD_TOKEN }}" "${{ secrets.SECURE_DOWNLOAD_URL }}" | gpg --yes --no-tty --import - > /dev/null 2>&1
            git config --local user.email "kluge-watchdog@bio.ifi.lmu.de"
            git config --local user.name "watchdog-wms-bot"
            git add -A
            git commit -S --gpg-sign="${{ secrets.KEY_FINGERPRINT }}" -m "updated documentation"
            gpg --yes --no-tty --batch --delete-secret-keys "${{ secrets.KEY_FINGERPRINT }}" > /dev/null 2>&1
            git push
          fi
